services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  adminer:
    depends_on: 
    - db
    container_name: adminer
    image: adminer
    restart: always
    ports: 
        - 8888:8080
  wordpress:
    build: .
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
 
networks: 
    back:
volumes:
  db_data: